
resultadosHistoricos = [
    {idUsuario:0, nombre:"Constanza", area:"matematica", puntos:1, tiempo:71},
    {idUsuario:1, nombre:"Andrea", area:"lenguaje", puntos:1, tiempo:33},
    {idUsuario:2, nombre:"Romina", area:"lenguaje", puntos:3, tiempo:45},
    {idUsuario:3, nombre:"Claudio", area:"lenguaje", puntos:3, tiempo:78},
    {idUsuario:4, nombre:"Susana", area:"matematica", puntos:0, tiempo:96},
    {idUsuario:5, nombre:"Hector", area:"matematica", puntos:2, tiempo:22},
    {idUsuario:6, nombre:"Gustavo", area:"lenguaje", puntos:0, tiempo:68},
    {idUsuario:7, nombre:"Lorena", area:"lenguaje", puntos:2, tiempo:94},
    {idUsuario:8, nombre:"Ana", area:"lenguaje", puntos:3, tiempo:107},
    {idUsuario:9, nombre:"Mario", area:"lenguaje", puntos:0, tiempo:58},
    {idUsuario:10, nombre:"Martina", area:"matematica", puntos:1, tiempo:141},
    {idUsuario:11, nombre:"Elba", area:"lenguaje", puntos:1, tiempo:62},
    {idUsuario:12, nombre:"Cintia", area:"lenguaje", puntos:3, tiempo:92},
    {idUsuario:13, nombre:"Andres", area:"lenguaje", puntos:0, tiempo:38},
    {idUsuario:14, nombre:"Facundo", area:"lenguaje", puntos:2, tiempo:84},
    {idUsuario:15, nombre:"Violeta", area:"lenguaje", puntos:3, tiempo:70},
    {idUsuario:16, nombre:"Camilo", area:"matematica", puntos:3, tiempo:107},
    {idUsuario:17, nombre:"Lautaro", area:"lenguaje", puntos:0, tiempo:58},
    {idUsuario:18, nombre:"Luis", area:"lenguaje", puntos:2, tiempo:90},
    {idUsuario:19, nombre:"Cesar", area:"lenguaje", puntos:2, tiempo:103},
    {idUsuario:20, nombre:"Leo", area:"matematica", puntos:2, tiempo:16},
    {idUsuario:21, nombre:"Guillermo", area:"matematica", puntos:1, tiempo:79},
    {idUsuario:22, nombre:"Micaela", area:"matematica", puntos:0, tiempo:46},
]

